# Generated by Django 4.2.30 on 2026-06-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0002_bloquehorario_rut_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquehorario',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Opcional. Define un bloque que se repite semanalmente en el día seleccionado.', null=True, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='fecha',
            field=models.DateField(blank=True, help_text='Opcional. Define un bloque válido solo para ese día concreto.', null=True, verbose_name='Fecha específica'),
        ),
    ]
